//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.3625
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.3038")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="DailyInfoSoap", Namespace="http://web.cbr.ru/")]
public partial class DailyInfo : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    /// <remarks/>
    public DailyInfo() {
        this.Url = "http://www.cbr.ru/dailyinfowebserv/dailyinfo.asmx";
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/SaldoXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode SaldoXML(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("SaldoXML", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaldoXML(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SaldoXML", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndSaldoXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/mrrf7D", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet mrrf7D(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("mrrf7D", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginmrrf7D(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("mrrf7D", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet Endmrrf7D(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/mrrf7DXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode mrrf7DXML(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("mrrf7DXML", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginmrrf7DXML(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("mrrf7DXML", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode Endmrrf7DXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/mrrf", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet mrrf(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("mrrf", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Beginmrrf(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("mrrf", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet Endmrrf(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/mrrfXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode mrrfXML(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("mrrfXML", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginmrrfXML(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("mrrfXML", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndmrrfXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/Saldo", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet Saldo(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("Saldo", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSaldo(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("Saldo", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndSaldo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/NewsInfoXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode NewsInfoXML(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("NewsInfoXML", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginNewsInfoXML(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("NewsInfoXML", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndNewsInfoXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/OmodInfoXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode OmodInfoXML() {
        object[] results = this.Invoke("OmodInfoXML", new object[0]);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginOmodInfoXML(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("OmodInfoXML", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndOmodInfoXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/XVol", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet XVol(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("XVol", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginXVol(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("XVol", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndXVol(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/XVolXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode XVolXML(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("XVolXML", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginXVolXML(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("XVolXML", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndXVolXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/MainInfoXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode MainInfoXML() {
        object[] results = this.Invoke("MainInfoXML", new object[0]);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginMainInfoXML(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("MainInfoXML", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndMainInfoXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/AllDataInfoXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode AllDataInfoXML() {
        object[] results = this.Invoke("AllDataInfoXML", new object[0]);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginAllDataInfoXML(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("AllDataInfoXML", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndAllDataInfoXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/NewsInfo", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet NewsInfo(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("NewsInfo", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginNewsInfo(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("NewsInfo", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndNewsInfo(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/SwapDynamicXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode SwapDynamicXML(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("SwapDynamicXML", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSwapDynamicXML(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SwapDynamicXML", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndSwapDynamicXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/SwapDynamic", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet SwapDynamic(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("SwapDynamic", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginSwapDynamic(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("SwapDynamic", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndSwapDynamic(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/DepoDynamicXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode DepoDynamicXML(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("DepoDynamicXML", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDepoDynamicXML(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DepoDynamicXML", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndDepoDynamicXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/DepoDynamic", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet DepoDynamic(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("DepoDynamic", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDepoDynamic(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DepoDynamic", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndDepoDynamic(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/OstatDynamicXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode OstatDynamicXML(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("OstatDynamicXML", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginOstatDynamicXML(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("OstatDynamicXML", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndOstatDynamicXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/OstatDynamic", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet OstatDynamic(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("OstatDynamic", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginOstatDynamic(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("OstatDynamic", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndOstatDynamic(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/DragMetDynamicXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode DragMetDynamicXML(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("DragMetDynamicXML", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDragMetDynamicXML(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DragMetDynamicXML", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndDragMetDynamicXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/DragMetDynamic", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet DragMetDynamic(System.DateTime fromDate, System.DateTime ToDate) {
        object[] results = this.Invoke("DragMetDynamic", new object[] {
                    fromDate,
                    ToDate});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDragMetDynamic(System.DateTime fromDate, System.DateTime ToDate, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DragMetDynamic", new object[] {
                    fromDate,
                    ToDate}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndDragMetDynamic(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetLatestDateTime", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.DateTime GetLatestDateTime() {
        object[] results = this.Invoke("GetLatestDateTime", new object[0]);
        return ((System.DateTime)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetLatestDateTime(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetLatestDateTime", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.DateTime EndGetLatestDateTime(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.DateTime)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetLatestDate", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetLatestDate() {
        object[] results = this.Invoke("GetLatestDate", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetLatestDate(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetLatestDate", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetLatestDate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetLatestDateTimeSeld", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.DateTime GetLatestDateTimeSeld() {
        object[] results = this.Invoke("GetLatestDateTimeSeld", new object[0]);
        return ((System.DateTime)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetLatestDateTimeSeld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetLatestDateTimeSeld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public System.DateTime EndGetLatestDateTimeSeld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.DateTime)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetLatestDateSeld", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string GetLatestDateSeld() {
        object[] results = this.Invoke("GetLatestDateSeld", new object[0]);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetLatestDateSeld(System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetLatestDateSeld", new object[0], callback, asyncState);
    }
    
    /// <remarks/>
    public string EndGetLatestDateSeld(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/EnumValutesXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode EnumValutesXML(bool Seld) {
        object[] results = this.Invoke("EnumValutesXML", new object[] {
                    Seld});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEnumValutesXML(bool Seld, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EnumValutesXML", new object[] {
                    Seld}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndEnumValutesXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/EnumValutes", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet EnumValutes(bool Seld) {
        object[] results = this.Invoke("EnumValutes", new object[] {
                    Seld});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginEnumValutes(bool Seld, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("EnumValutes", new object[] {
                    Seld}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndEnumValutes(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetCursDynamicXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode GetCursDynamicXML(System.DateTime FromDate, System.DateTime ToDate, string ValutaCode) {
        object[] results = this.Invoke("GetCursDynamicXML", new object[] {
                    FromDate,
                    ToDate,
                    ValutaCode});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCursDynamicXML(System.DateTime FromDate, System.DateTime ToDate, string ValutaCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCursDynamicXML", new object[] {
                    FromDate,
                    ToDate,
                    ValutaCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndGetCursDynamicXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetCursDynamic", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet GetCursDynamic(System.DateTime FromDate, System.DateTime ToDate, string ValutaCode) {
        object[] results = this.Invoke("GetCursDynamic", new object[] {
                    FromDate,
                    ToDate,
                    ValutaCode});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCursDynamic(System.DateTime FromDate, System.DateTime ToDate, string ValutaCode, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCursDynamic", new object[] {
                    FromDate,
                    ToDate,
                    ValutaCode}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGetCursDynamic(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetCursOnDateXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode GetCursOnDateXML(System.DateTime On_date) {
        object[] results = this.Invoke("GetCursOnDateXML", new object[] {
                    On_date});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCursOnDateXML(System.DateTime On_date, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCursOnDateXML", new object[] {
                    On_date}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndGetCursOnDateXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetSeldCursOnDateXML", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Xml.XmlNode GetSeldCursOnDateXML(System.DateTime On_date) {
        object[] results = this.Invoke("GetSeldCursOnDateXML", new object[] {
                    On_date});
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetSeldCursOnDateXML(System.DateTime On_date, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetSeldCursOnDateXML", new object[] {
                    On_date}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Xml.XmlNode EndGetSeldCursOnDateXML(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Xml.XmlNode)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetSeldCursOnDate", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet GetSeldCursOnDate(System.DateTime On_date) {
        object[] results = this.Invoke("GetSeldCursOnDate", new object[] {
                    On_date});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetSeldCursOnDate(System.DateTime On_date, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetSeldCursOnDate", new object[] {
                    On_date}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGetSeldCursOnDate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://web.cbr.ru/GetCursOnDate", RequestNamespace="http://web.cbr.ru/", ResponseNamespace="http://web.cbr.ru/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public System.Data.DataSet GetCursOnDate(System.DateTime On_date) {
        object[] results = this.Invoke("GetCursOnDate", new object[] {
                    On_date});
        return ((System.Data.DataSet)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginGetCursOnDate(System.DateTime On_date, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("GetCursOnDate", new object[] {
                    On_date}, callback, asyncState);
    }
    
    /// <remarks/>
    public System.Data.DataSet EndGetCursOnDate(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((System.Data.DataSet)(results[0]));
    }
}
